language: php

php:
- 7.1

before_script:
- composer self-update
- composer install --no-interaction
- composer require php-coveralls/php-coveralls

script:
- mkdir -p build/logs
- ./vendor/bin/paraunit cover -c phpunit.xml --parallel=4 --clover=build/logs/clover.xml --ansi

after_success:
- travis_retry php vendor/bin/php-coveralls